const clinicConfig={name:"Elite Medical Clinic",phone:"",whatsapp:"",email:"",address:"",instagram:"https://www.instagram.com/elite_medical_clinic_/",googleMaps:"https://maps.app.goo.gl/TGAwMYgdTLqkEHca7",verified:{name:true,phone:false,whatsapp:false,email:false,address:false,maps:false,instagram:true}};
const clinicData={tagline:"Professional Healthcare",description:"Verified clinic information will be displayed after the supplied sources are confirmed.",hours:[],services:[],doctors:[],treatments:[],reviews:[],gallery:[]};
const $=s=>document.querySelector(s);
document.addEventListener("DOMContentLoaded",()=>{render();nav();forms();reveal();lightbox();$("#year").textContent=new Date().getFullYear()});
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function empty(t){return `<div class="empty">${esc(t)}</div>`}
function render(){
$("#brandName").textContent=clinicConfig.name;$("#footerName").textContent=clinicConfig.name;$("#heroText").textContent=clinicData.description;$("#aboutText").textContent=clinicData.description;
$("#pills").innerHTML=Object.entries(clinicConfig.verified).filter(([,v])=>v).map(([k])=>`<span class="pill">${esc(k)} verified</span>`).join("")||'<span class="pill">Verification in progress</span>';
renderList("servicesGrid",clinicData.services,"No verified services have been added yet.",x=>`<article><b>+</b><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p></article>`);
renderList("teamGrid",clinicData.doctors,"Doctor/team information is pending verification.",x=>`<article><b>+</b><h3>${esc(x.name)}</h3><p>${esc(x.specialty||"")}</p><p>${esc(x.qualification||"")}</p></article>`);
renderList("treatmentsGrid",clinicData.treatments,"Verified treatments/specialties are not available yet.",x=>`<article><b>+</b><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p></article>`);
renderList("reviewsGrid",clinicData.reviews,"Verified Google review content has not been added.",x=>`<article><b>★★★★★</b><p>${esc(x.text)}</p><h3>${esc(x.author||"Patient")}</h3></article>`);
$("#galleryGrid").innerHTML=clinicData.gallery.length?clinicData.gallery.map((x,i)=>`<button data-i="${i}"><img src="${esc(x.src)}" alt="${esc(x.alt||"Clinic image")}" loading="lazy"></button>`).join(""):empty("No authorized clinic images have been added yet.");
$("#hours").innerHTML=clinicData.hours.length?clinicData.hours.map(x=>`<div class="hours-row"><strong>${esc(x.day)}</strong><span>${esc(x.hours)}</span></div>`).join(""):empty("Opening hours require verification.");
const rows=[];if(clinicConfig.verified.phone)rows.push(["Phone",`<a href="tel:${esc(clinicConfig.phone)}">${esc(clinicConfig.phone)}</a>`]);if(clinicConfig.verified.email)rows.push(["Email",`<a href="mailto:${esc(clinicConfig.email)}">${esc(clinicConfig.email)}</a>`]);if(clinicConfig.verified.address)rows.push(["Address",esc(clinicConfig.address)]);$("#contacts").innerHTML=rows.length?rows.map(r=>`<div class="contact-line"><strong>${r[0]}</strong><span>${r[1]}</span></div>`).join(""):empty("Verified phone, email and address information will appear here after confirmation.");
$("#instagram").href=clinicConfig.instagram;$("#footerInstagram").href=clinicConfig.instagram;$("#footerMaps").href=clinicConfig.googleMaps;$("#reviewsLink").href=clinicConfig.googleMaps;$("#directions").href=clinicConfig.googleMaps;$("#mapsVerify").href=clinicConfig.googleMaps;
if(CLINIC_LOCATION_VERIFICATION_REQUIRED)$("#verify").hidden=false;
if(clinicConfig.verified.whatsapp&&clinicConfig.whatsapp){$("#whatsapp").href="https://wa.me/"+clinicConfig.whatsapp.replace(/\D/g,"")+"?text="+encodeURIComponent("Hello, I would like to know more about your services and book an appointment.");$("#whatsapp").hidden=false}
$("#serviceSelect").innerHTML='<option value="">Select service</option>'+clinicData.services.map(x=>`<option>${esc(x.title)}</option>`).join("");
}
function renderList(id,arr,msg,fn){$( "#"+id).innerHTML=arr.length?arr.map(fn).join(""):empty(msg)}
function nav(){const b=$("#menuBtn"),m=$("#menu");b.onclick=()=>{m.classList.toggle("open");b.setAttribute("aria-expanded",m.classList.contains("open"))};document.addEventListener("click",e=>{if(!m.contains(e.target)&&e.target!==b)m.classList.remove("open")})}
function reveal(){const els=document.querySelectorAll(".reveal");if(!("IntersectionObserver"in window)){els.forEach(e=>e.classList.add("visible"));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");o.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>o.observe(e))}
function forms(){setupForm($("#appointmentForm"),$("#appointmentStatus"));setupForm($("#contactForm"),$("#contactStatus"))}
function setupForm(form,status){form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());if(data.website)return;if(!form.checkValidity()){form.reportValidity();return}if(!CONFIG.APPS_SCRIPT_URL||CONFIG.APPS_SCRIPT_URL.includes("PASTE_")){status.className="status err";status.textContent="Configure the Apps Script /exec URL in config.js first.";return}const btn=form.querySelector(".submit");btn.disabled=true;btn.textContent="Sending…";status.className="status loading";status.textContent="Sending…";data.source=CONFIG.SOURCE;data.pageUrl=location.href;try{const r=await fetch(CONFIG.APPS_SCRIPT_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(data)});const text=await r.text();let result;try{result=JSON.parse(text)}catch{throw Error("Invalid backend response.")}if(!r.ok||!result.success)throw Error(result.message||"Submission failed.");status.className="status ok";status.textContent=result.message||"Request received successfully.";form.reset()}catch(err){status.className="status err";status.textContent=err.message||"Unable to submit. Please try again."}finally{btn.disabled=false;btn.textContent=form.id==="appointmentForm"?"Send Appointment Request":"Send Inquiry"}}}
let gi=0;function lightbox(){const box=$("#lightbox"),img=$("#lightboxImage");$("#galleryGrid").onclick=e=>{const b=e.target.closest("button[data-i]");if(!b)return;gi=+b.dataset.i;img.src=clinicData.gallery[gi].src;img.alt=clinicData.gallery[gi].alt||"Clinic image";box.hidden=false;document.body.style.overflow="hidden"};$("#closeLightbox").onclick=close;$("#prevImage").onclick=()=>move(-1);$("#nextImage").onclick=()=>move(1);document.addEventListener("keydown",e=>{if(box.hidden)return;if(e.key==="Escape")close();if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1)});function move(d){if(!clinicData.gallery.length)return;gi=(gi+d+clinicData.gallery.length)%clinicData.gallery.length;img.src=clinicData.gallery[gi].src;img.alt=clinicData.gallery[gi].alt||"Clinic image"}function close(){box.hidden=true;document.body.style.overflow=""}}